apiVersion: batch/v1
kind: CronJob
metadata:
  name: mastodon-bot-cron
  labels:
    app.kubernetes.io/name: k8s-mastodon-bot
spec:
  schedule: "* */15 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: mastodon-bot
          containers:
            - image: domaindrivenarchitecture/mastodon-bot
              name: mastodon-bot
              env:
                - name: MASTODON_BOT_CREDENTIALS
                  value: /credentials.edn
              volumeMounts:
                - name: config-volume
                  mountPath: /config.edn
                  subPath: config.edn
                  readOnly: true
                - name: config-volume
                  mountPath: /credentials.edn
                  subPath: credentials.edn
                  readOnly: true
          restartPolicy: Never
        
