apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mastodon-bot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-mastodon-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-mastodon-bot
    spec:
      containers:
        - image: mastodon-bot
          name: mastodon-bot
          env:
            - name: MASTODON_BOT_CREDENTIALS
              value: /app/credentials.edn
          cmd:
          volumeMounts:
            - name: mastodon-bot
              mountPath: /app/config.edn
              subPath: config.conf
              readOnly: true
            - name: mastodon-bot
              mountPath: /app/credentials.edn
              subPath: credentials.conf
              readOnly: true
      
