apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mastodon-bot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-mastodon-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-mastodon-bot
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: mastodon-bot
      containers:
        - image: domaindrivenarchitecture/mastodon-bot
          name: mastodon-bot
          env:
            - name: MASTODON_BOT_CREDENTIALS
              value: /credentials.edn
          volumeMounts:
            - name: config-volume
              mountPath: /config.edn
              subPath: config.edn
              readOnly: true
            - name: config-volume
              mountPath: /credentials.edn
              subPath: credentials.edn
              readOnly: true
      
